name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        run: ctest --test-dir build --output-on-failure

      - name: Upload exe to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/Release/GeoTool.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
